-- 创味机 Ingredient 模块数据库表

-- 食材表（含调味品，通过 category 区分）
CREATE TABLE IF NOT EXISTS `ingredient` (
    `id`                BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
    `user_id`           BIGINT        NOT NULL                COMMENT '用户ID',
    `name`              VARCHAR(64)   NOT NULL                COMMENT '食材名称',
    `quantity`          DECIMAL(10,2) NOT NULL  DEFAULT 0     COMMENT '数量',
    `unit`              VARCHAR(16)   NOT NULL  DEFAULT ''    COMMENT '单位',
    `category`          VARCHAR(32)   NOT NULL  DEFAULT ''    COMMENT '分类',
    `storage_condition`  VARCHAR(32)            DEFAULT ''    COMMENT '存储条件',
    `expire_date`       DATE                    DEFAULT NULL  COMMENT '保质期',
    `readed`            TINYINT(1)   NOT NULL  DEFAULT 0     COMMENT '用户是否已确认临期提醒 0=未确认 1=已确认',
    `created_at`        DATETIME      NOT NULL  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`        DATETIME      NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_category` (`category`),
    INDEX `idx_expire_date` (`expire_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='食材表';

-- 常用食材表（系统预设，非用户数据）
CREATE TABLE IF NOT EXISTS `common_ingredient` (
    `id`            INT         NOT NULL AUTO_INCREMENT COMMENT '主键',
    `category`      VARCHAR(32) NOT NULL              COMMENT '分类',
    `name`          VARCHAR(64) NOT NULL              COMMENT '食材名称',
    `default_unit`  VARCHAR(16) NOT NULL DEFAULT ''   COMMENT '默认单位',
    PRIMARY KEY (`id`),
    INDEX `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='常用食材表';

-- 预置常用食材数据
INSERT INTO `common_ingredient` (`category`, `name`, `default_unit`) VALUES
('蔬菜', '西红柿', '个'),
('蔬菜', '鸡蛋', '个'),
('蔬菜', '青椒', '个'),
('蔬菜', '土豆', '个'),
('蔬菜', '洋葱', '个'),
('蔬菜', '胡萝卜', '根'),
('蔬菜', '白菜', '颗'),
('蔬菜', '黄瓜', '根'),
('蔬菜', '茄子', '个'),
('蔬菜', '西蓝花', '颗'),
('肉类', '猪肉', '克'),
('肉类', '牛肉', '克'),
('肉类', '鸡肉', '克'),
('肉类', '羊肉', '克'),
('肉类', '排骨', '克'),
('肉类', '鸡翅', '个'),
('肉类', '鸡腿', '个'),
('肉类', '五花肉', '克'),
('水产', '鱼', '条'),
('水产', '虾', '克'),
('水产', '螃蟹', '只'),
('水产', '鱿鱼', '条'),
('蛋类', '鸡蛋', '个'),
('蛋类', '鸭蛋', '个'),
('蛋类', '鹌鹑蛋', '个'),
('乳制品', '牛奶', '盒'),
('乳制品', '酸奶', '盒'),
('乳制品', '奶酪', '片'),
('豆制品', '豆腐', '块'),
('豆制品', '豆腐皮', '张'),
('豆制品', '腐竹', '根'),
('豆制品', '豆芽', '克'),
('谷物', '大米', '克'),
('谷物', '面粉', '克'),
('谷物', '面条', '克'),
('调味品', '盐', '克'),
('调味品', '糖', '克'),
('调味品', '酱油', '毫升'),
('调味品', '醋', '毫升'),
('调味品', '料酒', '毫升'),
('调味品', '生抽', '毫升'),
('调味品', '老抽', '毫升'),
('调味品', '蚝油', '毫升'),
('调味品', '豆瓣酱', '克'),
('调味品', '辣椒酱', '克'),
('调味品', '番茄酱', '克'),
('调味品', '胡椒粉', '克'),
('调味品', '花椒', '克'),
('调味品', '八角', '个'),
('调味品', '桂皮', '块'),
('调味品', '香叶', '片'),
('调味品', '味精', '克'),
('调味品', '鸡精', '克'),
('调味品', '淀粉', '克'),
('调味品', '食用油', '毫升'),
('调味品', '香油', '毫升'),
('水果', '苹果', '个'),
('水果', '香蕉', '根'),
('水果', '橙子', '个'),
('水果', '葡萄', '克'),
('其他', '面包', '片'),
('其他', '饼干', '盒'),
('其他', '蜂蜜', '克'),
('其他', '枸杞', '克'),
('其他', '红枣', '颗');

-- 用户订阅表（微信订阅消息授权记录）
CREATE TABLE IF NOT EXISTS `ingredient_subscription` (
    `id`            BIGINT      NOT NULL AUTO_INCREMENT COMMENT '主键',
    `user_id`       BIGINT      NOT NULL                COMMENT '用户ID',
    `subscribed`    TINYINT(1)  NOT NULL DEFAULT 0      COMMENT '是否开启提醒 0=关闭 1=开启',
    `created_at`    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='食材提醒订阅表';
