spring:
  application:
    name: backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080

jwt:
  expiration: 300000
  refresh-expiration: 2592000000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

flcr:
  storage:
    local-path: ./uploads
    url-prefix: /uploads
  token:
    store: memory

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  default-produces-media-type: application/json

llm:
  api:
    url: "https://api.siliconflow.cn/v1/chat/completions"
    model: "Pro/zai-org/GLM-4.7"
    key: "Bearer sk-pwtinglhtvzmzvbgempceozorwujlepqtxarjfslbzsvmrnx"
