spring:
  application:
    name: backend
  profiles:
    active: dev

server:
  port: 8080

jwt:
  expiration: 7200000
  refresh-expiration: 604800000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true