spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

wx:
  app-id: ${WX_APP_ID}
  secret: ${WX_SECRET}

jwt:
  secret: ${JWT_SECRET}

mybatis-plus:
  configuration:
    log-impl: none